#!/bin/bash
set -eo pipefail

# force mysql to not use the local unix socket (test "external" connectibility)
host="$(hostname --ip-address || echo '127.0.0.1')"

if select="$(echo 'SELECT 1' | mysql -s -h $host -u root)" && [ "$select" = '1' ]; then
	exit 0
fi

exit 1
